<?php
define('LOGGER_LEVEL_DEBUG',		1);
define('LOGGER_LEVEL_INFO',			2);
define('LOGGER_LEVEL_WARN',			3);
define('LOGGER_LEVEL_ERROR',		4);
define('LOGGER_LEVEL_FATAL',		5);

define('LOGGER_LEVEL_DEFAULT', LOGGER_LEVEL_DEBUG);